In [70]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import requests
import json
#from config.py import gkey

In [71]:
#tried to use BreweryDB.com API to make a database; however, a paid subscription is required.

# params = {'gkey' : gkey, 
#           'format' : 'json', 
#           'name' : 'RiseofthePhoenix'}
# base_url = 'https://api.brewerydb.com/v2/'
# request = requests.get(base_url, params=params)
# beer_pd = request.json()
# beer_pd
# {'message': 'Request Successful',

#  'data': 'You have reached the BreweryDB.com API.  For access, check out http://www.brewerydb.com/developers',
#  'status': 'success'}

In [81]:
#import data found in https://www.kaggle.com/nickhould/craft-cans
beer_df = pd.read_csv('Resource/beers.csv')
breweries_df = pd.read_csv('Resource/breweries.csv')
beer_df.head()

,Unnamed: 0,abv,ibu,id,name,style,brewery_id,ounces
0,0,0.050,NaN,1436,Pub Beer,American Pale Lager,408,12.0
1,1,0.066,NaN,2265,Devil's Cup,American Pale Ale (APA),177,12.0
2,2,0.071,NaN,2264,Rise of the Phoenix,American IPA,177,12.0
3,3,0.090,NaN,2263,Sinister,American Double / Imperial IPA,177,12.0
4,4,0.075,NaN,2262,Sex and Candy,American IPA,177,12.0

In [82]:
#clean data RE:beer.csv
#remove the ibu, ounces from data
beer_df = beer_df[['id','name','abv','style','brewery_id']]
beer_df.head()
beer_df.info()
#there are 2410 beers in this list. We need to clean the data and remove the blank data.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2410 entries, 0 to 2409
Data columns (total 5 columns):
id            2410 non-null int64
name          2410 non-null object
abv           2348 non-null float64
style         2405 non-null object
brewery_id    2410 non-null int64
dtypes: float64(1), int64(2), object(2)
memory usage: 94.2+ KB

In [91]:
beer_df = beer_df.dropna(axis=0, how='any')
beer_df['style'].value_counts()

American IPA                           417
American Pale Ale (APA)                239
American Amber / Red Ale               125
American Blonde Ale                    104
American Double / Imperial IPA         103
American Pale Wheat Ale                 95
American Brown Ale                      68
American Porter                         65
Saison / Farmhouse Ale                  52
Witbier                                 49
Fruit / Vegetable Beer                  49
Kölsch                                  42
Hefeweizen                              39
American Pale Lager                     37
American Stout                          37
Cider                                   37
German Pilsener                         36
American Black Ale                      35
Märzen / Oktoberfest                    29
Cream Ale                               28
American Amber / Red Lager              28
Czech Pilsener                          28
American Pilsner                        24
Belgian Pale Ale                        23
Pumpkin Ale                             23
Vienna Lager                            20
Munich Helles Lager                     20
Extra Special / Strong Bitter (ESB)     19
Rye Beer                                18
American Adjunct Lager                  18
                                      ...
Munich Dunkel Lager                      4
Irish Dry Stout                          4
Dunkelweizen                             4
Quadrupel (Quad)                         4
Chile Beer                               3
English Pale Mild Ale                    3
Radler                                   3
Shandy                                   3
Keller Bier / Zwickel Bier               3
English Barleywine                       3
English Bitter                           3
American India Pale Lager                3
American Barleywine                      3
Old Ale                                  2
American Double / Imperial Pilsner       2
Roggenbier                               2
Abbey Single Ale                         2
Euro Pale Lager                          2
Rauchbier                                2
Wheat Ale                                1
Flanders Red Ale                         1
American Malt Liquor                     1
Other                                    1
Braggot                                  1
Grisette                                 1
Smoked Beer                              1
English Stout                            1
Low Alcohol Beer                         1
Flanders Oud Bruin                       1
Kristalweizen                            1
Name: style, Length: 99, dtype: int64

In [84]:
#clean data RE:breweries.csv
#rename unamed column to be able to merge data
breweries_df = breweries_df.rename(columns = {'Unnamed: 0':'brewery_id'})
breweries_df.head()
breweries_df.info()
#there are 558 different breweries

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558 entries, 0 to 557
Data columns (total 4 columns):
brewery_id    558 non-null int64
name          558 non-null object
city          558 non-null object
state         558 non-null object
dtypes: int64(1), object(3)
memory usage: 17.5+ KB

In [85]:

test = beer_df['brewery_id'].nunique()
test

546

In [86]:

test2 = breweries_df['brewery_id'].nunique()
test2

558

In [56]:
unique_style = pd.DataFrame(beer_df['style'].unique())

In [57]:
unique_style

                                     0
0                  American Pale Lager
1              American Pale Ale (APA)
2                         American IPA
3       American Double / Imperial IPA
4                        Oatmeal Stout
5                      American Porter
6               Saison / Farmhouse Ale
7                          Belgian IPA
8                                Cider
9                        Baltic Porter
10                              Tripel
11                 American Barleywine
12                       Winter Warmer
13                      American Stout
14              Fruit / Vegetable Beer
15                  English Strong Ale
16                  American Black Ale
17                    Belgian Dark Ale
18                 American Blonde Ale
19            American Amber / Red Ale
20                  Berliner Weissbier
21                  American Brown Ale
22             American Pale Wheat Ale
23             Belgian Strong Dark Ale
24                              Kölsch
25                    English Pale Ale
26          American Amber / Red Lager
27                  English Barleywine
28                  Milk / Sweet Stout
29                     German Pilsener
..                                 ...
70                              Dubbel
71                    Quadrupel (Quad)
72              Russian Imperial Stout
73               English Pale Mild Ale
74               Maibock / Helles Bock
75                Herbed / Spiced Beer
76              American Adjunct Lager
77                        Scottish Ale
78                                 NaN
79                         Smoked Beer
80                         Light Lager
81                    Abbey Single Ale
82                          Roggenbier
83                       Kristalweizen
84             American Dark Wheat Ale
85                       English Stout
86                             Old Ale
87  American Double / Imperial Pilsner
88                    Flanders Red Ale
89          Keller Bier / Zwickel Bier
90           American India Pale Lager
91                              Shandy
92                           Wheat Ale
93                American Malt Liquor
94                      English Bitter
95                          Chile Beer
96                            Grisette
97                  Flanders Oud Bruin
98                             Braggot
99                    Low Alcohol Beer

[100 rows x 1 columns]